# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['modern_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('questions.txt', '.'),
    ],
    hiddenimports=[
        'playwright.sync_api',
        'pyperclip',
        'chardet',
        'PIL',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'customtkinter',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.ctk_button',
        'customtkinter.windows.widgets.ctk_entry',
        'customtkinter.windows.widgets.ctk_label',
        'customtkinter.windows.widgets.ctk_textbox',
        'customtkinter.windows.widgets.ctk_progressbar',
        'customtkinter.windows.widgets.ctk_scrollable_frame',
        'customtkinter.windows.widgets.ctk_tabview',
        'customtkinter.windows.widgets.ctk_combobox',
        'pystray',
        'pystray._win32',
        'pystray._darwin',
        'pystray._xorg',
        'flask',
        'flask.json',
        'flask.json.tag',
        'urllib3',
        'itsdangerous',
        'werkzeug',
        'jinja2',
        'click',
        'blinker',
        'markupsafe',
        'six',
        'python_xlib',
        'darkdetect',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AI网页全自动批量处理工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
